# Generated by Django 5.2.8 on 2025-12-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=25)),
                ('course_name', models.CharField(max_length=25)),
                ('course_duration', models.IntegerField()),
                ('seat', models.IntegerField()),
            ],
        ),
    ]
